### ISSUE TITLE
Error thrown for unpinning items

### ISSUE THREAD

**Issue by st0nebreaker** [etcetera8/copy-pasta#18]
Pinning behavior preforms as expected. However when unpinning happens, an error is thrown.

My hunch is it's from the concated arrays on `Landing`'s render?

Branch name: `feature/pinning-items`

<img width="551" alt="Screen Shot 2021-02-01 at 5 13 34 PM" src="https://user-images.githubusercontent.com/59381432/106540655-3c645a80-64b5-11eb-9096-73968c71c4a6.png">
<img width="792" alt="Screen Shot 2021-02-01 at 5 19 38 PM" src="https://user-images.githubusercontent.com/59381432/106540657-3d958780-64b5-11eb-90aa-d194df47e523.png">

**Comment by etcetera8** [comment]
So first thing I'd like to see is rather than a "pinningData" method and an "unPinning" lets just go ahead and make a "togglePinnedStatus".

**Comment by etcetera8** [comment]
In `src/renderer/components/Row.tsx` line 36 through 47 the only difference I'm seeing between those two buttons is the icon. We can clean up a of those extra lines by just making a ternary in the img src attribute i.e. `<img src={pinned ? pinIcon : unpinnedIcon} alt="pin icon" />

Also, for boolean type variables I like to use the word "is" before the thing that is a boolean. In this case, I think "isPinned" would read easier than just "pinned"

**Comment by st0nebreaker** [comment]
For sure. Sounds good. MobX is punking me in dev environment. Maybe we can pair in the next few days on this. Would be quicker.

**Comment by st0nebreaker** [comment]
⬆️ Scratch that, got it handled. Those refactors seemed to fix the unpinning issue. So this issue is resolved. Moving convo over to search issue.

**Comment by etcetera8** [comment]
Awesome. Sometimes it be like that. I figured it may help at least solve it so that’s good. 

For future ref you don’t have to close issues manually. You can close them in the PR via writing “resolves #18”

**Comment by b-stein** [comment]
Ohh. Can I re-open this issue so we can have it linked to the coming PR?
